### ISSUE TITLE
Deobfuscator

### ISSUE THREAD

**Issue by Someone-NEW** [ThisTestUser/deobfuscator-gui#1]
@ThisTestUser Hey how going about work and implemented ZKM 9 and anti releaking remover inside deobfuscator? maybe the separate plugin? I need cracked ZKM 9 for obfuscation that i send to you.
Please tell me something new. do you have Discord?

**Comment by ThisTestUser** [comment]
Unfortunately I don't have time to crack ZKM 9, it seems that they use the strongest string obfuscation, and I can't decrypt that.
Discord: https://discord.gg/PSDYZD

**Comment by Someone-NEW** [comment]
I am already Joined with SomeOne tnx you can delete link.
