### ISSUE TITLE
Download Please

### ISSUE THREAD

**Issue by THERALWEAN231** [ThisTestUser/deobfuscator-gui#2]

**Comment by ThisTestUser** [comment]
https://github.com/ThisTestUser/deobfuscator-gui/releases

**Comment by THERALWEAN231** [comment]
i should have know sorry for wasteing your time

**Comment by THERALWEAN231** [comment]
it says Could not locate a class file.
Have you added the necessary files to the -path argument?

**Comment by THERALWEAN231** [comment]
what do i do

**Comment by ThisTestUser** [comment]
Add all the libraries. If you already have a command, you can use load config.
Use this for more information: https://github.com/java-deobfuscator/deobfuscator
